# Generated by Django 4.1.2 on 2024-07-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0002_publicacion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='id_imagen',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='nombre_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombre_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='titulo por defecto', max_length=200),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redSocialGatitesApp.publicacion'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
