# Generated by Django 5.0.6 on 2024-06-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0002_publicacion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='id_imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redSocialGatitesApp.imagen'),
        ),
    ]
