# Generated by Django 5.0.6 on 2024-06-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0003_alter_perfil_usuario_id_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
