# Generated by Django 5.0.6 on 2024-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0004_alter_perfil_usuario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
