# Generated by Django 5.0.6 on 2024-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0005_remove_perfil_usuario_id_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_usuario',
            name='nombre_imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
