# Generated by Django 5.0.6 on 2024-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0006_perfil_usuario_nombre_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombre_imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url_imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
