# Generated by Django 5.0.6 on 2024-06-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocialGatitesApp', '0007_remove_publicacion_id_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='titulo por defecto', max_length=200),
        ),
    ]
